# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
builds:
  - binary: hijri-holiday
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

